#%RAML 1.0
title: University Directory Experience API
version: 1.0
protocols: [HTTP, HTTPS]
mediaType: application/json
securedBy: securities-fragment.clientIdEnforcement

uses:
  commons-fragment: /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/common-fragment/1.0.0/commons-fragment.raml
  securities-fragment: /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/securities-fragment/1.0.1/securities-fragment.raml
  domain-fragment: /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/domain-fragment.raml

/students:
  is:
    - commons-fragment.hasCommonHeaders
    - commons-fragment.hasRateLimiting
  type:
    commons-fragment.createReadCollection: {
      getResponseType: domain-fragment.studentGetResponseDataType,
      getResponseExample: !include /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/examples/studentListGetResponseExample.json,
      postResponseExample: !include /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/examples/studentCreateResponseExample.json
    }
  get:
    is:
      - commons-fragment.hasCacheable
    queryParameters:
      lastName?:
        description: Filter by last name
        example: Spark
        type: string
      firstName?:
        description: Filter by last name
        example: Tony
        type: string
      subjects?:
        description: Filter by last name
        example: [Physics, Political Science]
        type: array
        items:
          type: string
  post:
    body:
      application/json:
        type: domain-fragment.studentCreateRequestDataType
        example: !include /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/examples/studentCreateRequestExample.json
  /{studentId}:
    type:
      commons-fragment.readUpdateDeleteItem: {
        getResponseType: domain-fragment.studentGetResponseDataType,
        getResponseExample: !include /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/examples/studentGetResponseExample.json,
        patchResponseExample: !include /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/examples/studentUpdateResponseExample.json,
        deleteResponseExample: !include /exchange_modules/4d19cb17-975a-49d0-9cf7-d514ca2710f0/domain-fragment/1.0.0/examples/studentDeleteResponseExample.json
    }
    get:
      is:
        - commons-fragment.hasCommonHeaders
        - commons-fragment.hasRateLimiting